# Generated by Django 2.2.5 on 2020-06-02 21:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=8, verbose_name='会议室地址')),
                ('state', models.BooleanField(default=0, verbose_name='会议室状态')),
                ('info', models.CharField(default='小型会议室', max_length=24, verbose_name='会议室信息')),
            ],
            options={
                'verbose_name_plural': '会议室信息',
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='姓名')),
                ('gender', models.BooleanField(verbose_name='性别')),
                ('phone', models.CharField(max_length=24, verbose_name='联系方式')),
                ('create_date', models.TimeField(default=datetime.datetime(2020, 6, 2, 21, 27, 48, 609891), verbose_name='创建时间')),
                ('department', models.CharField(max_length=200, verbose_name='公司部门')),
                ('position', models.CharField(max_length=24, verbose_name='职位')),
                ('password', models.CharField(max_length=24, verbose_name='密码')),
                ('faceId', models.TextField(default=0, max_length=131070, verbose_name='人脸信息')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='会议主题')),
                ('order_time', models.DateTimeField(default=datetime.datetime(2020, 6, 2, 21, 27, 48, 610638), verbose_name='预订时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('note', models.CharField(max_length=200, verbose_name='备注信息')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationSys.Room', verbose_name='会议室编号')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationSys.Staff', verbose_name='员工编号')),
            ],
            options={
                'verbose_name_plural': '订单信息',
                'db_table': 'Booking',
            },
        ),
    ]
