# Generated by Django 2.2.5 on 2020-06-02 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationSys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 21, 28, 6, 700948), verbose_name='预订时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='create_date',
            field=models.TimeField(default=datetime.datetime(2020, 6, 2, 21, 28, 6, 700140), verbose_name='创建时间'),
        ),
    ]
