# Generated by Django 2.2.5 on 2020-06-02 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationSys', '0002_auto_20200602_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 21, 33, 37, 185759), verbose_name='预订时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='create_date',
            field=models.TimeField(default=datetime.datetime(2020, 6, 2, 21, 33, 37, 185031), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.BooleanField(default=True, verbose_name='性别'),
        ),
    ]
